### ISSUE TITLE
Is there any easy way to connect via CURL?

### ISSUE THREAD

**Issue by beshoo** [poe-platform/server-bot-quick-start#17]
Dear all , i want to connect to POE via PHP-CURL directly, please is there any documentation which will guide me to do that,

**Comment by gemuzkm** [comment]
Instead of opening up the API for access to bots, they gave access to an ordinary bot, which is not a problem to create anyway.

**Comment by anmolsingh95** [comment]
This is an API to access the bots on Poe, usage will count against your personal limits: https://developer.poe.com/server-bots/accessing-other-bots-on-poe
