### ISSUE TITLE
Poe Web Api / NPM Package

### ISSUE THREAD

**Issue by RohanDaCoder** [poe-platform/server-bot-quick-start#19]
Dear developers,
i just Want to say that you should make a web api like a post endpoint that will take json to commiunicate with the api. and there is an discord bot commiunity that can use ai to like use that on discord (im acually here for that lol) ...

So Pleaseeee add an web api or a npm package

**Comment by juukee** [comment]
so do i

**Comment by SonicandTailsCD** [comment]
> Dear developers, i just Want to say that you should make a web api like a post endpoint that will take json to commiunicate with the api. and there is an discord bot commiunity that can use ai to like use that on discord (im acually here for that lol) ...
> 
> So Pleaseeee add an web api or a npm package

I have to admit! I'd love that a lot! :D

**Comment by anmolsingh95** [comment]
We have a Discord that you can join using this link: https://discord.gg/TKxT6kBpgm
