### ISSUE TITLE
Error when querying hugging face model 

### ISSUE THREAD

**Issue by Shivak11** [poe-platform/server-bot-quick-start#56]
I tried the huggingface bot script. I am encountering a 404 error. Looks likes MODAL is expecting the model to be run locally. Is that correct?

**Comment by anmolsingh95** [comment]
I just tried the huggingface script and it seems or be working for me. We are the `AsyncInferenceClient` from the `huggingface_hub` library. According to the comments in the code:
> The model to run inference with. Can be a model id hosted on the Hugging Face Hub, e.g. `bigcode/starcoder` or a URL to a deployed Inference Endpoint. Defaults to None, in which case a recommended model is automatically selected for the task.
