### ISSUE TITLE
requirements.txt file is missing

### ISSUE THREAD

**Issue by imtiyazakiwat** [poe-platform/server-bot-quick-start#66]
The project is missing the "requirements.txt" file.

**Comment by tonghuikang** [comment]
Each bot now has it own individual Python requirements (which can be different between bots)

```
REQUIREMENTS = ["fastapi-poe==0.0.24"]
image = Image.debian_slim().pip_install(*REQUIREMENTS)
```

I think you still need libraries like modal and fastapi-poe to deploy the bots. Therefore, I think we should still have a requirements.txt for the entire project.

For now, if there are missing libraries when you try to deploy or serve Modal, you just pip install what is missing.

**Comment by anmolsingh95** [comment]
Just added back the top level requirements.txt. The modal-client library wasn't included in this file as it's recommended that you install the latest version.
